name: Log Analyzer CI

on:
  push:
    paths:
      - "application.log"
      - "analyzer.py"

jobs:
  analyze_logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run analyzer
      run: python analyzer.py

    - name: Commit updated summary.json back to repo
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add summary.json
        git commit -m "Auto-update summary.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload summary artifact
      uses: actions/upload-artifact@v4
      with:
        name: log-summary
        path: summary.json
